# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7381e2e2b355a80d8dcd42eabb49dbf7f7059ba53461f2c52dfd1fb27a761016536a3f353e9627b0489e1ac8cf7f007cee14b0e3f752a45d8050ffb74e7b530c

test:
  secret_key_base: 28fc6a25acdaf708c1f02c664e678fcfea89e0e83cc1f4cce0f2cc0ffeeb30802a1749ab32a750eeda2a17e445d5b5172003d91ca508653eaf0e15677f2546ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
